### ISSUE TITLE
Documentation of NvBlastExtUnity_x64.dll wanted but not found

### ISSUE THREAD

**Issue by nsolkp** [ElasticSea/destructible-walls#10]
I search for documentation of NvBlastExtUnity_x64.dll then I got this project : https://github.com/NVIDIAGameWorks/Blast.
But I still cannot find the specific doc of NvBlastExtUnity_x64.dll.

**Comment by geeks-eng** [comment]
Hi, I am also facing the same issue. You have closed this as completed. Did you find a solution for this or closed this because no solution was found?
